### ISSUE TITLE
How do i compile it?

### ISSUE THREAD

**Issue by turtiustrek** [byteandahalf/mc10_testmod#63]
So i got VS 2017 and i went in C++ and made a WIN32 Program and ticked dll i copied the source file to my source file and cant compile it any help would be amazing!

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1169	one or more multiply defined symbols found	test4	G:\Visual Studio\test4\Debug\test4.dll	1	
Error	LNK2005	_DllMain@12 already defined in dllmain.obj	test4	G:\Visual Studio\test4\test4\test4.obj	1

**Comment by byteandahalf** [comment]
Delete the build files and try again. Also make sure that you are building for x64 if you are on a 64-bit machine.

**Comment by turtiustrek** [comment]
i got it to compile but nothing changes in Minecraft Windows 10 edition i got a feeling that the Vftables are different and not updated in this code. Help?

**Comment by turtiustrek** [comment]
so every update the table change?

**Comment by ghost** [comment]
Yes the offsets change with updates, open up Minecraft.Windows.exe in a disassembler and find them again.

**Comment by ghost** [comment]
Oh also in the instruction video he uses Process Hacker to inject the DLL but I've tried everything and can't get it to inject into recent versions of MCW10, but Cheat Engine did it fine. Go to memory view and then tools -> inject dll. Make sure it's on Minecraft.Windows.exe not ApplicationFrameHost.exe

**Comment by MohammadMubin** [comment]
Interesting it seems like minecraft blocks the injection of the dll file itself ....

**Comment by turtiustrek** [comment]
So i re compiled the code with new offsets. Opened up mine craft and inject it in with Process Hacker and no results but with Cheat Engine it gives a result. Can anyone explain why is this happening?

**Comment by ghost** [comment]
What is your code?
